name: ola_maps
description: "OLA Maps - API"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^7.0.7+1
  json_annotation: ^4.8.1
  collection: ^1.17.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  chopper_generator: ^7.0.5+1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^3.0.0
  swagger_dart_code_generator: ^2.12.1
